language: perl
perl:
  - "5.26"
  - "5.10"

before_install:
  - cpanm --notest Test::Code::TidyAll
  - cpanm --notest Perl::Critic
  - cpanm --notest Test::Perl::Critic
  - cpanm --notest Perl::Tidy
  - cpanm --notest Devel::Cover::Report::Coveralls
script:
  perl Build.PL && ./Build build && cover -test -report coveralls

os:
  - linux

env:
  - TEST_AUTHOR=1